#!/bin/bash

choice(){
echo
echo 
echo
echo "$a | $b | $c"
echo "------------"
echo "$d | $e | $f"
echo "------------"
echo "$g | $h | $i"
echo
echo =====================
echo =====================

}
win(){

if [[ $1 = 'O' ]] && [[ $2 = 'O' ]] && [[ $3 = 'O' ]];
then 
	echo
	echo
	echo       YOU WIN!!! 
	echo       
	echo
	exit
elif [[ $1 = 'X' ]] && [[ $2 = 'X' ]] && [[ $3 = 'X' ]];
then
	echo
	echo
	echo       YOU LOSE!!
	echo
	exit
else echo
fi
}

winpattern(){

win $a $b $c
win $d $e $f
win $g $h $i
win $a $s $g
win $b $e $h
win $c $f $i
win $a $e $i
win $c $e $g

}
abc(){ 
a='1'
b='2'
c='3'
d='4'
e='5'
f='6'
g='7'
h='8'
i='9'
}
answercase(){
read -p 'your turn! choose a number: ' answer
if echo "${fill[@]}" | grep " "$answer" " ;
then
	echo
	echo 'Please choose a correct number and try again'
	echo
else
	case $answer in 
	1)
	a='O'
	((trial++))
	;;
	2)
	b='O'
	((trial++))
	;;
	3)
	c='O'
	((trial++))
	;;
	4)
	d='O'
	((trial++))
	;;
	5)
	e='O'
	((trial++))
	;;
	6)
	f='O'
	((trial++))
	;;
	7)
	g='O'
	((trial++))
	;;
	8)
	h='O'
	((trial++))
	;;
	9)
	i='O'
	((trial++))
	;;
	*)
	echo 'Please choose a correct number and try again'
	esac
	
fi
}
enermy(){
	echo
		if echo "${fill[@]}" | grep " "$1" " ;
		then
	echo	
	else
		case "$1" in 
		1)
		a='X'
		((opponent++))
		;;
		2)
		b='X'
		((opponent++))
		;;
		3)
		c='X'
		((opponent++))
		;;
		4)
		d='X'
		((opponent++))
		;;
		5)
		e='X'
		((opponent++))
		;;
		6)
		f='X'
		((opponent++))
		;;
		7)
		g='X'
		((opponent++))
		;;
		8)
		h='X'
		((opponent++))
		;;
		9)
		i='X'
		((opponent++))
		;;
		*)
		echo
		esac
	fi

}
flow1(){
	trial='1'
	choice
	while [ $trial = '1' ]
	do
		answercase
		fill+=(""$answer" ")
	done
	choice
	gameturn=$(( $gameturn + 1 ))
	winpattern
	trial='1'
}
flow2(){
	opponent='1'
	echo ${fill[@]}
	while [ $opponent = '1' ]
	do
		number=$(( $RANDOM % 10 ))
		shuffle=$( echo $number )
		enermy "$shuffle"
		fill+=(""$shuffle" ")
	done
	gameturn=$(( $gameturn + 1 ))
	opponent='1'
}
abc
gameturn=1
whole=1
fill=()
fill+=('0')
until [ $gameturn = 10 ] ; 
do
flow1
echo Computer has made a move
flow2 > /dev/null 2>&1
winpattern	
choice
done
exit

